name = "planner-rousset-backend"
main = "src/index.js"
workers_dev = true
preview_urls = true
compatibility_date = "2025-10-08"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_id = "c0eb72ac-8085-45b1-86e3-dc51c1af7e8a"
